/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * 幻灯片元素枚举
 *
 * 通过 JSON 中的 "type" 字段自动反序列化为对应的元素类型。 支持：text, shape, line, image, table, group 以及高级组件。
 */
export type Element =
  | {
      type: "text";
      /**
       * 稳定 ID（来自/写入 p:cNvPr/@id），用于 `@id=N` 寻址；生成时缺省自动分配
       */
      id?: number | null;
      /**
       * 文本内容（简单字符串或多段落）
       */
      text: TextContent;
      /**
       * 位置和尺寸
       */
      position: Position;
      /**
       * 元素名称
       */
      name?: string | null;
      /**
       * 占位符引用 `type|idx`（来自 p:ph，用于保留占位符语义）
       */
      placeholder?: string | null;
      /**
       * 字体大小（磅）
       */
      font_size?: number | null;
      /**
       * 加粗
       */
      bold?: boolean | null;
      /**
       * 斜体
       */
      italic?: boolean | null;
      /**
       * 下划线
       */
      underline?: boolean | null;
      /**
       * 文字颜色
       */
      color?: string | null;
      /**
       * 字体名称
       */
      font_family?: string | null;
      /**
       * 水平对齐：left, center, right, justify
       */
      align?: string | null;
      /**
       * 垂直对齐：top, middle, bottom
       */
      vert_align?: string | null;
      /**
       * 文字方向：horz（横向，默认）/ vert（纵向）
       */
      vert?: string | null;
      /**
       * 行距倍数（如 1.0 单倍 / 1.2 / 1.5），段落级优先
       */
      line_spacing?: number | null;
      /**
       * 是否自动换行（默认 true）
       */
      wrap?: boolean | null;
      /**
       * 文本背景填充
       */
      fill?: Fill | null;
      /**
       * 文本背景透明度
       */
      fill_alpha?: number | null;
      /**
       * 文本边框线
       */
      line?: Line | null;
      /**
       * 文本边框透明度
       */
      line_alpha?: number | null;
      /**
       * 阴影效果
       */
      shadow?: Shadow | null;
      /**
       * 其他效果：发光/倒影/柔化边缘/模糊/内阴影/填充覆盖
       */
      effects?: Effects | null;
      /**
       * 文本自适应（normAutofit / spAutoFit / noAutofit）
       */
      autofit?: Autofit | null;
      /**
       * 元素的动画列表
       */
      animations?: Animation[] | null;
      [k: string]: unknown;
    }
  | {
      type: "shape";
      /**
       * 稳定 ID（来自/写入 p:cNvPr/@id），用于 `@id=N` 寻址；生成时缺省自动分配
       */
      id?: number | null;
      /**
       * 形状类型：rect, roundRect, ellipse, triangle, rightArrow 等
       */
      shape_type: string;
      /**
       * 位置和尺寸
       */
      position: Position;
      /**
       * 元素名称
       */
      name?: string | null;
      /**
       * 占位符引用 `type|idx`（来自 p:ph，用于保留占位符语义）
       */
      placeholder?: string | null;
      /**
       * 旋转角度（度）
       */
      rotation?: number | null;
      /**
       * 填充色
       */
      fill?: Fill | null;
      /**
       * 填充透明度（0~1）
       */
      fill_alpha?: number | null;
      /**
       * 是否不填充
       */
      no_fill?: boolean | null;
      /**
       * 边框线
       */
      line?: Line | null;
      /**
       * 边框透明度（0~1）
       */
      line_alpha?: number | null;
      /**
       * 阴影效果
       */
      shadow?: Shadow | null;
      /**
       * 其他效果：发光/倒影/柔化边缘/模糊/内阴影/填充覆盖
       */
      effects?: Effects | null;
      /**
       * 文本自适应（normAutofit / spAutoFit / noAutofit）
       */
      autofit?: Autofit | null;
      /**
       * 形状调整参数（如圆角矩形的圆角大小）
       */
      adjust?: {
        [k: string]: number;
      } | null;
      /**
       * 形状内的文字
       */
      text?: TextContent | null;
      /**
       * 文字字体大小
       */
      font_size?: number | null;
      /**
       * 文字颜色
       */
      color?: string | null;
      /**
       * 文字对齐方式（水平：left, center, right, justify）
       */
      align?: string | null;
      /**
       * 文字垂直对齐：top, middle, bottom
       */
      vert_align?: string | null;
      /**
       * 行距倍数（如 1.0 单倍 / 1.2 / 1.5），段落级优先
       */
      line_spacing?: number | null;
      /**
       * 动画列表
       */
      animations?: Animation[] | null;
      [k: string]: unknown;
    }
  | {
      type: "line";
      /**
       * 稳定 ID（来自/写入 p:cNvPr/@id），用于 `@id=N` 寻址；生成时缺省自动分配
       */
      id?: number | null;
      /**
       * 位置和尺寸（线条的包围盒）
       */
      position: Position;
      /**
       * 元素名称
       */
      name?: string | null;
      /**
       * 顶点列表（英寸，相对 position 原点；两点为直线，多点折线）
       */
      points?: [number, number][];
      /**
       * 线条颜色（默认主题强调色）
       */
      color?: string | null;
      /**
       * 线条宽度（磅，默认 1.0）
       */
      width?: number | null;
      /**
       * 虚线样式：solid / dashed / dotted
       */
      dash?: string | null;
      /**
       * 起点端点：none / arrow / dot
       */
      arrow_start?: string | null;
      /**
       * 终点端点：none / arrow / dot
       */
      arrow_end?: string | null;
      /**
       * 是否平滑曲线（true 时相邻顶点间用二次贝塞尔连接）
       */
      smooth?: boolean | null;
      /**
       * 旋转角度（度）
       */
      rotation?: number | null;
      /**
       * 元素的动画列表
       */
      animations?: Animation[] | null;
      [k: string]: unknown;
    }
  | {
      type: "image";
      /**
       * 稳定 ID（来自/写入 p:cNvPr/@id），用于 `@id=N` 寻址；生成时缺省自动分配
       */
      id?: number | null;
      /**
       * 图片源路径（本地路径或 URL）
       */
      src: string;
      /**
       * 位置和尺寸
       */
      position: Position;
      /**
       * 元素名称
       */
      name?: string | null;
      /**
       * 旋转角度（度）
       */
      rotation?: number | null;
      /**
       * 裁剪参数
       */
      crop?: Crop | null;
      /**
       * 超链接 URL
       */
      hyperlink?: string | null;
      /**
       * 图片边框
       */
      line?: Line | null;
      /**
       * 亮度调整（-1.0 ~ 1.0）
       */
      brightness?: number | null;
      /**
       * 对比度调整（-1.0 ~ 1.0）
       */
      contrast?: number | null;
      /**
       * 填充模式：stretch（默认）/ contain / cover / tile
       */
      fill_mode?: string | null;
      /**
       * 悬浮提示文字
       */
      tooltip?: string | null;
      /**
       * 关联的媒体（视频/音频，src 为媒体文件，图片本身作为封面）
       */
      media?: MediaRef | null;
      /**
       * 动画列表
       */
      animations?: Animation[] | null;
      [k: string]: unknown;
    }
  | {
      type: "icon";
      /**
       * 稳定 ID（来自/写入 p:cNvPr/@id），用于 `@id=N` 寻址；生成时缺省自动分配
       */
      id?: number | null;
      /**
       * 位置和尺寸
       */
      position: Position;
      /**
       * 图标名称（内置 SVG 库）
       */
      icon: string;
      /**
       * 图标颜色
       */
      color?: string | null;
      /**
       * 元素名称
       */
      name?: string | null;
      /**
       * 旋转角度（度）
       */
      rotation?: number | null;
      /**
       * 图标边框
       */
      line?: Line | null;
      /**
       * 动画列表
       */
      animations?: Animation[] | null;
      [k: string]: unknown;
    }
  | {
      type: "formula";
      /**
       * 稳定 ID（来自/写入 p:cNvPr/@id），用于 `@id=N` 寻址；生成时缺省自动分配
       */
      id?: number | null;
      /**
       * 位置和尺寸
       */
      position: Position;
      /**
       * 公式 LaTeX 文本
       */
      latex: string;
      /**
       * 公式文字颜色
       */
      color?: string | null;
      /**
       * 元素名称
       */
      name?: string | null;
      /**
       * 旋转角度（度）
       */
      rotation?: number | null;
      /**
       * 文本内容（降级时用，可与 latex 同源）
       */
      text?: TextContent | null;
      /**
       * 字体大小
       */
      font_size?: number | null;
      /**
       * 动画列表
       */
      animations?: Animation[] | null;
      [k: string]: unknown;
    }
  | {
      type: "table";
      /**
       * 稳定 ID（来自/写入 p:cNvPr/@id），用于 `@id=N` 寻址；生成时缺省自动分配
       */
      id?: number | null;
      /**
       * 位置和尺寸
       */
      position: Position;
      /**
       * 元素名称
       */
      name?: string | null;
      /**
       * 表格行数据（每行包含多个单元格）
       */
      rows: Cell[][];
      /**
       * 每列宽度（英寸，缺省均分表格总宽）
       */
      column_widths?: number[] | null;
      /**
       * 是否将第一行作为表头
       */
      header_row?: boolean | null;
      /**
       * 内置表格样式 ID（GUID，如 {5C22544A-...}）
       */
      style_id?: string | null;
      /**
       * 是否从右到左
       */
      rtl?: boolean | null;
      /**
       * 各行高度（英寸）
       */
      row_heights?: number[] | null;
      /**
       * 原始 a:tblPr 属性（firstRow/firstCol/bandRow 等，原样保留）
       */
      tbl_attrs?: string | null;
      /**
       * 默认字体大小
       */
      font_size?: number | null;
      /**
       * 默认文字颜色
       */
      color?: string | null;
      /**
       * 动画列表
       */
      animations?: Animation[] | null;
      [k: string]: unknown;
    }
  | {
      type: "chart";
      /**
       * 稳定 ID（来自/写入 p:cNvPr/@id），用于 `@id=N` 寻址；生成时缺省自动分配
       */
      id?: number | null;
      /**
       * 位置和尺寸
       */
      position: Position;
      /**
       * 元素名称
       */
      name?: string | null;
      /**
       * 图表类型：column, bar, line, pie, doughnut, area, scatter, radar
       */
      chart_type: string;
      /**
       * 图表标题
       */
      title?: string | null;
      /**
       * 分类标签
       */
      categories?: string[];
      /**
       * 数据系列
       */
      series?: ChartSeries[];
      /**
       * 是否显示图例
       */
      legend?: boolean | null;
      /**
       * 图例位置：top, bottom, left, right, topRight
       */
      legend_position?: string | null;
      /**
       * 原始图表部件 XML（保留完整样式；生成时优先原样回写）
       */
      raw?: string | null;
      /**
       * 动画列表
       */
      animations?: Animation[] | null;
      [k: string]: unknown;
    }
  | {
      type: "comment";
      /**
       * 批注锚点位置（英寸）
       */
      position: Position;
      /**
       * 作者
       */
      author?: string | null;
      /**
       * 批注内容
       */
      text: string;
      [k: string]: unknown;
    }
  | {
      type: "equation";
      /**
       * 稳定 ID（来自/写入 p:cNvPr/@id），用于 `@id=N` 寻址；生成时缺省自动分配
       */
      id?: number | null;
      /**
       * 位置和尺寸
       */
      position: Position;
      /**
       * 元素名称
       */
      name?: string | null;
      /**
       * 原始 OMML 数学 XML（`a14:m` 子树）
       */
      omml: string;
      /**
       * 纯文本近似（用于查询/预览）
       */
      text?: string | null;
      [k: string]: unknown;
    }
  | {
      type: "opaque";
      /**
       * 稳定 ID（来自/写入 p:cNvPr/@id），用于 `@id=N` 寻址；生成时缺省自动分配
       */
      id?: number | null;
      /**
       * 位置和尺寸
       */
      position: Position;
      /**
       * 元素名称
       */
      name?: string | null;
      /**
       * 原始元素 XML（rId 为原始值）
       */
      xml: string;
      /**
       * 引用的关系
       */
      rels?: OpaqueRel[];
      /**
       * 关系指向的内部部件
       */
      parts?: OpaquePart[];
      /**
       * 提取的纯文本（用于查询/预览）
       */
      text?: string | null;
      [k: string]: unknown;
    }
  | {
      type: "group";
      /**
       * 稳定 ID（来自/写入 p:cNvPr/@id），用于 `@id=N` 寻址；生成时缺省自动分配
       */
      id?: number | null;
      /**
       * 分组位置和尺寸
       */
      position: Position;
      /**
       * 分组名称
       */
      name?: string | null;
      /**
       * 旋转角度（度）
       */
      rotation?: number | null;
      /**
       * 子元素列表
       */
      children: Element[];
      /**
       * 分组的动画列表
       */
      animations?: Animation[] | null;
      [k: string]: unknown;
    }
  | {
      type: "progress_bar";
      /**
       * 组件位置和尺寸
       */
      position: Position;
      /**
       * 进度值 0-100
       */
      value?: number | null;
      /**
       * 进度条颜色
       */
      color?: string | null;
      /**
       * 轨道（背景条）颜色
       */
      track_color?: string | null;
      /**
       * 是否圆角
       */
      rounded?: boolean | null;
      /**
       * 是否显示标签
       */
      show_label?: boolean | null;
      /**
       * 自定义标签文字（缺省显示百分比）
       */
      label?: string | null;
      /**
       * 标签文字颜色
       */
      text_color?: string | null;
      /**
       * 标签字号
       */
      font_size?: number | null;
      [k: string]: unknown;
    }
  | {
      type: "progress_ring";
      /**
       * 组件位置和尺寸
       */
      position: Position;
      /**
       * 进度值 0-100
       */
      value?: number | null;
      /**
       * 进度弧颜色
       */
      color?: string | null;
      /**
       * 轨道环颜色
       */
      track_color?: string | null;
      /**
       * 环的粗细（点）
       */
      thickness?: number | null;
      /**
       * 是否显示中心百分比
       */
      show_label?: boolean | null;
      /**
       * 中心文字颜色
       */
      text_color?: string | null;
      /**
       * 中心文字字号
       */
      font_size?: number | null;
      [k: string]: unknown;
    }
  | {
      type: "bar_chart";
      /**
       * 组件位置和尺寸
       */
      position: Position;
      /**
       * 数据值数组，每个值一根柱（旧版 JSON 的 value 字段仍兼容）
       */
      data: number[];
      /**
       * 底部标签数组
       */
      labels?: string[] | null;
      /**
       * 每根柱的颜色数组
       */
      colors?: string[] | null;
      /**
       * 纵轴最大值（用于计算柱高比例）
       */
      max?: number | null;
      /**
       * 柱顶显示数值
       */
      show_values?: boolean | null;
      /**
       * 显示坐标轴
       */
      axis?: boolean | null;
      /**
       * 标签颜色
       */
      label_color?: string | null;
      /**
       * 标签字号
       */
      font_size?: number | null;
      [k: string]: unknown;
    }
  | {
      type: "line_chart";
      /**
       * 组件位置和尺寸
       */
      position: Position;
      /**
       * 数据值数组，每个值一个数据点（旧版 JSON 的 value 字段仍兼容）
       */
      data: number[];
      /**
       * 底部标签数组
       */
      labels?: string[] | null;
      /**
       * 折线颜色（可传数组，缺省单色）
       */
      colors?: string[] | null;
      /**
       * 纵轴最大值（用于计算点高比例）
       */
      max?: number | null;
      /**
       * 数据点上方显示数值
       */
      show_values?: boolean | null;
      /**
       * 显示坐标轴
       */
      axis?: boolean | null;
      /**
       * 是否平滑曲线
       */
      smooth?: boolean | null;
      /**
       * 标签颜色
       */
      label_color?: string | null;
      /**
       * 标签字号
       */
      font_size?: number | null;
      [k: string]: unknown;
    }
  | {
      type: "pie_chart";
      /**
       * 组件位置和尺寸
       */
      position: Position;
      /**
       * 数据值数组，每个值一个扇区（旧版 JSON 的 value 字段仍兼容）
       */
      data: number[];
      /**
       * 扇区标签数组
       */
      labels?: string[] | null;
      /**
       * 每个扇区的颜色数组
       */
      colors?: string[] | null;
      /**
       * 扇区外侧显示百分比
       */
      show_values?: boolean | null;
      /**
       * 标签颜色
       */
      label_color?: string | null;
      /**
       * 标签字号
       */
      font_size?: number | null;
      [k: string]: unknown;
    }
  | {
      type: "ring_chart";
      /**
       * 组件位置和尺寸
       */
      position: Position;
      /**
       * 数据值数组，每个值一个环段（旧版 JSON 的 value 字段仍兼容）
       */
      data: number[];
      /**
       * 环段标签数组
       */
      labels?: string[] | null;
      /**
       * 每个环段的颜色数组
       */
      colors?: string[] | null;
      /**
       * 环的粗细（占半径比例，0~1，默认 0.35）
       */
      thickness?: number | null;
      /**
       * 外侧显示百分比
       */
      show_values?: boolean | null;
      /**
       * 标签颜色
       */
      label_color?: string | null;
      /**
       * 标签字号
       */
      font_size?: number | null;
      [k: string]: unknown;
    }
  | {
      type: "kpi_card";
      /**
       * 组件位置和尺寸
       */
      position: Position;
      /**
       * 主数值（大号粗体显示）
       */
      value: string;
      /**
       * 小标题
       */
      label?: string | null;
      /**
       * 变化指示（正数绿色 / 负数红色）
       */
      delta?: string | null;
      /**
       * 卡片背景色
       */
      bg?: string | null;
      /**
       * 强调条颜色
       */
      accent?: string | null;
      /**
       * 卡片圆角
       */
      rounded?: boolean | null;
      /**
       * 文字颜色
       */
      text_color?: string | null;
      [k: string]: unknown;
    }
  | {
      type: "rating_stars";
      /**
       * 组件位置和尺寸
       */
      position: Position;
      /**
       * 评分值（旧版 JSON 的 value 字段仍兼容）
       */
      rating: number;
      /**
       * 星星总数（默认 5）
       */
      max?: number | null;
      /**
       * 已点亮星星颜色
       */
      color?: string | null;
      /**
       * 未点亮星星颜色
       */
      empty_color?: string | null;
      [k: string]: unknown;
    }
  | {
      type: "timeline";
      /**
       * 组件位置和尺寸
       */
      position: Position;
      /**
       * 时间节点数组（date/title/desc 等，旧版 JSON 的 value 字段仍兼容）
       */
      items: unknown[];
      /**
       * 基线颜色
       */
      line_color?: string | null;
      /**
       * 圆点颜色
       */
      dot_color?: string | null;
      /**
       * 标签颜色
       */
      label_color?: string | null;
      [k: string]: unknown;
    }
  | {
      type: "process_flow";
      /**
       * 组件位置和尺寸
       */
      position: Position;
      /**
       * 步骤名称数组（旧版 JSON 的 value 字段仍兼容）
       */
      steps: string[];
      /**
       * 每步的圆角矩形颜色
       */
      colors?: string[] | null;
      /**
       * 步骤文字颜色
       */
      text_color?: string | null;
      /**
       * 步骤字号
       */
      font_size?: number | null;
      [k: string]: unknown;
    };
/**
 * 文本内容的两种表示方式
 */
export type TextContent = string | Paragraph[];
/**
 * 填充类型：纯色、渐变或图案
 */
export type Fill =
  | string
  | {
      /**
       * 渐变停止点列表
       */
      stops: GradientStop[];
      /**
       * 渐变角度（度）
       */
      angle?: number | null;
      [k: string]: unknown;
    }
  | {
      /**
       * 图案预设名（如 pct20, diagCross, smallGrid 等 OOXML prst 值）
       */
      pattern: string;
      /**
       * 前景色
       */
      fg: string;
      /**
       * 背景色
       */
      bg: string;
      [k: string]: unknown;
    }
  | {
      /**
       * 图片路径/URL
       */
      src: string;
      [k: string]: unknown;
    };

/**
 * 演示文稿顶层结构
 *
 * 包含整份演示文稿的所有配置和数据。 可作为 JSON 输入进行 PPTX 生成，也可作为 PPTX 解析的输出。
 */
export interface Presentation {
  /**
   * 幻灯片宽度（英寸），默认 13.333（宽屏 16:9）
   */
  width?: number;
  /**
   * 幻灯片高度（英寸），默认 7.5（宽屏 16:9）
   */
  height?: number;
  /**
   * 元信息（可选）
   */
  meta?: Meta | null;
  /**
   * 模板名称（可选），对应 TemplatePreset 中的预设名称
   */
  template?: string | null;
  /**
   * 主题配置（可选），包含颜色方案和字体
   */
  theme?: Theme | null;
  /**
   * 幻灯片列表
   */
  slides: Slide[];
  /**
   * 原始 ppt/tableStyles.xml（保留内置表格样式/banding；缺省则生成默认）
   */
  table_styles?: string | null;
  [k: string]: unknown;
}
/**
 * 演示文稿元信息（标题、作者）
 */
export interface Meta {
  /**
   * 演示文稿标题
   */
  title?: string | null;
  /**
   * 作者名称
   */
  author?: string | null;
  /**
   * 公司
   */
  company?: string | null;
  /**
   * 生成程序（如 Microsoft Office PowerPoint）
   */
  application?: string | null;
  /**
   * 最后修改者
   */
  last_modified_by?: string | null;
  [k: string]: unknown;
}
/**
 * 演示文稿主题，包含颜色方案和字体设置
 *
 * 颜色键值对说明： - dk1/dk2: 深色，lt1/lt2: 浅色 - accent1~accent6: 强调色 - hlink/folHlink: 超链接颜色
 */
export interface Theme {
  /**
   * 颜色方案映射表
   */
  colors?: {
    [k: string]: string;
  } | null;
  /**
   * 主要字体（标题用）
   */
  major_font?: string | null;
  /**
   * 次要字体（正文用）
   */
  minor_font?: string | null;
  [k: string]: unknown;
}
/**
 * 单张幻灯片
 */
export interface Slide {
  /**
   * 幻灯片中的元素列表（文本、形状、图片等）
   */
  elements: Element[];
  /**
   * 背景设置 - 字符串: 纯色背景，如 "#FFFFFF" - 对象: 渐变背景或图片背景
   */
  background?: {
    [k: string]: unknown;
  };
  /**
   * 幻灯片过渡动画
   */
  transition?: Transition | null;
  /**
   * 演讲者备注（纯文本，多行用换行符分隔）
   */
  notes?: string | null;
  [k: string]: unknown;
}
/**
 * 段落，包含多个 TextRun 或纯文本
 */
export interface Paragraph {
  /**
   * 文本运行片段列表（精细格式控制）
   */
  runs?: TextRun[] | null;
  /**
   * 纯文本内容（无格式分段时使用）
   */
  text?: string | null;
  /**
   * 段落级字体大小
   */
  font_size?: number | null;
  /**
   * 段落级加粗
   */
  bold?: boolean | null;
  /**
   * 段落级斜体
   */
  italic?: boolean | null;
  /**
   * 段落级文字颜色
   */
  color?: string | null;
  /**
   * 对齐方式：left, center, right, justify
   */
  align?: string | null;
  /**
   * 行距倍数（如 1.0 单倍 / 1.2 / 1.5）
   */
  line_spacing?: number | null;
  /**
   * 是否显示项目符号
   */
  bullet?: boolean | null;
  [k: string]: unknown;
}
/**
 * 一个文本运行片段（相同格式的一段文字）
 */
export interface TextRun {
  /**
   * 文本内容
   */
  text: string;
  /**
   * 字体大小（磅）
   */
  font_size?: number | null;
  /**
   * 加粗
   */
  bold?: boolean | null;
  /**
   * 斜体
   */
  italic?: boolean | null;
  /**
   * 下划线
   */
  underline?: boolean | null;
  /**
   * 文字颜色
   */
  color?: string | null;
  /**
   * 字体名称
   */
  font_family?: string | null;
  /**
   * 超链接地址（网页 URL）
   */
  hyperlink?: string | null;
  /**
   * 高亮背景色（十六进制）
   */
  highlight?: string | null;
  /**
   * 下划线颜色（十六进制）
   */
  underline_color?: string | null;
  /**
   * 字符间距（磅，可为负）
   */
  spacing?: number | null;
  /**
   * 语言标签（如 zh-CN）
   */
  lang?: string | null;
  /**
   * 是否从右到左
   */
  rtl?: boolean | null;
  [k: string]: unknown;
}
/**
 * 元素在幻灯片上的位置和尺寸（英寸单位）
 */
export interface Position {
  /**
   * X 坐标（左上角）
   */
  x: number;
  /**
   * Y 坐标（左上角）
   */
  y: number;
  /**
   * 宽度
   */
  w: number;
  /**
   * 高度
   */
  h: number;
  [k: string]: unknown;
}
/**
 * 渐变停止点
 */
export interface GradientStop {
  /**
   * 停止点颜色
   */
  color: string;
  /**
   * 停止点位置（0~1）
   */
  position: number;
  [k: string]: unknown;
}
/**
 * 线条样式
 */
export interface Line {
  /**
   * 线条颜色
   */
  color: string;
  /**
   * 线条宽度（磅），默认 1.0
   */
  width?: number;
  [k: string]: unknown;
}
/**
 * 阴影效果
 */
export interface Shadow {
  /**
   * 模糊半径（磅），默认 4.0
   */
  blur?: number;
  /**
   * 阴影距离（磅），默认 3.0
   */
  distance?: number;
  /**
   * 阴影角度（度），默认 45.0
   */
  angle?: number;
  /**
   * 不透明度（0~1），默认 0.4
   */
  opacity?: number;
  /**
   * 阴影颜色
   */
  color?: string;
  [k: string]: unknown;
}
/**
 * 效果集合
 */
export interface Effects {
  /**
   * 发光
   */
  glow?: Glow | null;
  /**
   * 是否启用倒影
   */
  reflection?: boolean | null;
  /**
   * 柔化边缘半径（磅）
   */
  soft_edge?: number | null;
  /**
   * 模糊半径（磅）
   */
  blur?: number | null;
  /**
   * 内阴影
   */
  inner_shadow?: Shadow | null;
  /**
   * 填充覆盖
   */
  fill_overlay?: FillOverlay | null;
  [k: string]: unknown;
}
/**
 * 发光效果
 */
export interface Glow {
  /**
   * 发光颜色（十六进制）
   */
  color: string;
  /**
   * 半径（磅）
   */
  radius?: number;
  /**
   * 不透明度（0~1）
   */
  opacity?: number | null;
  [k: string]: unknown;
}
/**
 * 填充覆盖效果
 */
export interface FillOverlay {
  /**
   * 覆盖颜色
   */
  color: string;
  /**
   * 不透明度（0~1）
   */
  opacity?: number | null;
  [k: string]: unknown;
}
/**
 * 文本自适应设置（bodyPr 的 normAutofit / spAutoFit / noAutofit）
 */
export interface Autofit {
  /**
   * none | shape | normal
   */
  kind: string;
  /**
   * 字号缩放比例（0~1，normal 时）
   */
  font_scale?: number | null;
  /**
   * 行距缩减比例（0~1，normal 时）
   */
  ln_spc_reduction?: number | null;
  [k: string]: unknown;
}
/**
 * 元素动画效果
 *
 * 支持进入、退出、强调和路径动画四大类。 触发方式支持：onClick（点击）、afterPrevious（之后）、withPrevious（同时）。
 */
export interface Animation {
  /**
   * 动画类型：appear, fadeIn, fadeOut, flyIn, flyOut, zoomIn, zoomOut, wipeIn, wipeOut, bounceIn, floatIn, floatOut, swivel, dissolveIn, dissolveOut, splitIn, pulse, spin, growShrink, colorChange, transparency, teeter, blink, motionPath
   */
  type: string;
  /**
   * 动画持续时间（毫秒）
   */
  duration?: number | null;
  /**
   * 动画延迟（毫秒）
   */
  delay?: number | null;
  /**
   * 触发方式：onClick, afterPrevious, withPrevious
   */
  trigger?: string | null;
  /**
   * 方向：top, bottom, left, right 等
   */
  direction?: string | null;
  /**
   * 动画执行顺序
   */
  order?: number | null;
  /**
   * 缩放比例（百分比）
   */
  scale?: number | null;
  /**
   * 旋转角度（度）
   */
  degrees?: number | null;
  /**
   * 颜色变化目标色
   */
  color?: string | null;
  /**
   * 透明度变化目标值
   */
  opacity?: number | null;
  /**
   * 路径动画的关键点
   */
  points?:
    | {
        [k: string]: number;
      }[]
    | null;
  /**
   * 动画移动距离（英寸）
   */
  distance?: number | null;
  /**
   * 重复次数（数字字符串或 "indefinite"）
   */
  repeat?: string | null;
  /**
   * 重启方式（如 "whenNotActive"）
   */
  restart?: string | null;
  /**
   * 是否自动反向播放
   */
  auto_reverse?: boolean | null;
  [k: string]: unknown;
}
/**
 * 图片裁剪参数（EMU 单位）
 */
export interface Crop {
  /**
   * 左侧裁剪距离
   */
  left?: number;
  /**
   * 顶部裁剪距离
   */
  top?: number;
  /**
   * 右侧裁剪距离
   */
  right?: number;
  /**
   * 底部裁剪距离
   */
  bottom?: number;
  [k: string]: unknown;
}
/**
 * 媒体引用（视频 / 音频）
 */
export interface MediaRef {
  /**
   * 类型：video / audio
   */
  kind: string;
  /**
   * 媒体文件路径或 URL
   */
  src: string;
  [k: string]: unknown;
}
/**
 * 表格单元格
 */
export interface Cell {
  /**
   * 单元格文字内容
   */
  text: string;
  /**
   * 字体大小
   */
  font_size?: number | null;
  /**
   * 加粗
   */
  bold?: boolean | null;
  /**
   * 文字颜色
   */
  color?: string | null;
  /**
   * 单元格背景色
   */
  fill?: string | null;
  /**
   * 对齐方式：left, center, right
   */
  align?: string | null;
  /**
   * 横向合并的列数（缺省 1）
   */
  colspan?: number | null;
  /**
   * 纵向合并的行数（缺省 1）
   */
  rowspan?: number | null;
  /**
   * 单元格边框
   */
  border?: CellBorder | null;
  /**
   * 文字方向：horz（默认）/ vert
   */
  vert?: string | null;
  /**
   * 单元格内边距 [left, top, right, bottom]（英寸）
   *
   * @minItems 4
   * @maxItems 4
   */
  margin?: [number, number, number, number] | null;
  /**
   * 单元格图片填充（图片路径/URL）
   */
  fill_image?: string | null;
  /**
   * 单元格垂直对齐：t（默认）/ ctr / b
   */
  anchor?: string | null;
  [k: string]: unknown;
}
/**
 * 单元格边框（四边同色同宽）
 */
export interface CellBorder {
  /**
   * 边框颜色
   */
  color: string;
  /**
   * 边框宽度（磅）
   */
  width?: number;
  [k: string]: unknown;
}
/**
 * 图表数据系列
 */
export interface ChartSeries {
  /**
   * 系列名称
   */
  name?: string | null;
  /**
   * 系列数值
   */
  values?: number[];
  /**
   * 系列颜色（十六进制）
   */
  color?: string | null;
  [k: string]: unknown;
}
/**
 * 元素引用的关系（生成时按新 rId 重写，Target 保持不变）
 */
export interface OpaqueRel {
  /**
   * 原始关系 Id（如 rId5）
   */
  old_id: string;
  /**
   * 关系类型（完整 URI）
   */
  rel_type: string;
  /**
   * 目标（相对路径或外部 URL）
   */
  target: string;
  /**
   * 是否外部关系
   */
  external?: boolean;
  [k: string]: unknown;
}
/**
 * 关系指向的内部部件（含传递闭包）
 */
export interface OpaquePart {
  /**
   * 包内路径（如 ppt/diagrams/data1.xml）
   */
  path: string;
  /**
   * 内容类型
   */
  content_type: string;
  /**
   * 字节内容（base64）
   */
  data: string;
  /**
   * 该部件自身的关系文件内容（若有）
   */
  rels_xml?: string | null;
  [k: string]: unknown;
}
/**
 * 幻灯片切换时的过渡动画
 */
export interface Transition {
  /**
   * 过渡类型：fade, push, wipe, split, cover, cut, dissolve, random
   */
  type: string;
  /**
   * 过渡速度：slow, med, fast
   */
  speed?: string | null;
  /**
   * 是否点击鼠标时切换
   */
  advance_on_click?: boolean | null;
  /**
   * 自动切换延时（毫秒）
   */
  advance_after?: number | null;
  [k: string]: unknown;
}
